# Generated by Django 3.2.5 on 2021-07-10 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.SmallIntegerField()),
                ('weight', models.SmallIntegerField()),
                ('maxCP', models.PositiveSmallIntegerField()),
                ('family_name', models.CharField(max_length=100)),
                ('base_attack', models.PositiveSmallIntegerField()),
                ('base_defense', models.PositiveSmallIntegerField()),
                ('base_stamina', models.PositiveSmallIntegerField()),
                ('primary_type', models.CharField(choices=[('NR', 'Normal'), ('FR', 'Fire'), ('WT', 'Water'), ('GS', 'Grass'), ('EL', 'Electric'), ('IC', 'Ice'), ('FT', 'Fighting'), ('PO', 'Poison'), ('GD', 'Ground'), ('FL', 'Flying'), ('PY', 'Psychic'), ('BG', 'Bug'), ('RK', 'Rock'), ('DK', 'Dark'), ('DG', 'Dragon'), ('ST', 'Steel'), ('FA', 'Fairy')], default='NR', max_length=100)),
                ('secondary_type', models.CharField(blank=True, choices=[('NR', 'Normal'), ('FR', 'Fire'), ('WT', 'Water'), ('GS', 'Grass'), ('EL', 'Electric'), ('IC', 'Ice'), ('FT', 'Fighting'), ('PO', 'Poison'), ('GD', 'Ground'), ('FL', 'Flying'), ('PY', 'Psychic'), ('BG', 'Bug'), ('RK', 'Rock'), ('DK', 'Dark'), ('DG', 'Dragon'), ('ST', 'Steel'), ('FA', 'Fairy')], max_length=100)),
                ('evolution', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pokemon_base.pokemon')),
            ],
        ),
    ]
