# Generated by Django 3.2.5 on 2021-07-13 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('pokemon_base', '0002_auto_20210711_2318'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormPokemon',
        ),
        migrations.RenameField(
            model_name='pokemon',
            old_name='infancy_gender',
            new_name='evolve_gender',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='infancy',
        ),
        migrations.RemoveField(
            model_name='pokemon',
            name='regional_variant',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='evolves_from',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                                       related_name='evolves_to', to='pokemon_base.pokemon'),
        ),
        migrations.DeleteModel(
            name='RegionalPokemon',
        ),
    ]
